# Generated by Django 4.0.6 on 2024-06-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_categ_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categ',
            name='image',
            field=models.ImageField(default=0, upload_to='product'),
            preserve_default=False,
        ),
    ]
